spring:
  flyway:
    validate-on-migrate: true
    baseline-version: "1"
  application:
    name: spring-boot-2025-rest-aws-gcp-java-docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_UDEMY?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none # importante na utilizacao de migration (somente leitura)
    properties:
      hibernate:
        show-sql: false
        open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

cors:
  originPatterns: http://localhost:8080,http://prontuarios-jaala.com
file:
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
email:
  subject: "Default Subject"
  message: "Default Message"
logging:
  level:
    root: INFO
    net.sf.jasperreports.engine.*: TRACE
    br.com.sbrwgjd: debug
  spring-doc:
    paths-to-match: /api/**/v1/
    swagger-ui:
      use-root-path: true

