spring:
  flyway:
    validate-on-migrate: true
    baseline-version: "1"
  application:
    name: spring-boot-2025-rest-aws-gcp-java-docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_UDEMY?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none # importante na utilizacao de migration (somente leitura)
    properties:
      hibernate:
        show-sql: false
        open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

cors:
  originPatterns: http://localhost:8080,http://prontuarios-jaala.com
file:
  upload-dir: /Code/UploadDir

logging:
  level:
    root: INFO
    net.sf.jasperreports.engine.*: TRACE
    br.com.sbrwgjd: debug
  spring-doc:
    paths-to-match: /api/**/v1/
    swagger-ui:
      use-root-path: true

